"""Added choices and questions

Revision ID: 79dad7924e61
Revises: 265e8a36ee5e
Create Date: 2016-01-11 17:35:31.882738

"""

# revision identifiers, used by Alembic.
revision = '79dad7924e61'
down_revision = '265e8a36ee5e'
branch_labels = None
depends_on = None

import datetime
import websauna.system.model.columns

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('question_text', sa.String(length=256), nullable=True),
    sa.Column('published_at', websauna.system.model.columns.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice')
    op.drop_table('question')
    ### end Alembic commands ###
