"""Added choices and questions 2

Revision ID: 9aea23bfff8b
Revises: 79dad7924e61
Create Date: 2016-01-11 18:14:59.369550

"""

# revision identifiers, used by Alembic.
revision = '9aea23bfff8b'
down_revision = '79dad7924e61'
branch_labels = None
depends_on = None

import datetime
import websauna.system.model.columns

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('choice_text', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'choice_text')
    ### end Alembic commands ###
